runtime: nodejs
env: flex

env_variables:
  SQL_USERNAME: root
  SQL_PASSWORD: yB5dsbAmy2hAArEq
  SQL_DATABASE_NAME: devoid
  SQL_CONNECTION_NAME: devoid-api:us-east1:devoid-database

beta_settings:
  cloud_sql_instances: devoid-api:us-east1:devoid-database